name: GitHub Actions Demo 
run-name: Testing out GitHub Actions_demo run by ${{ github.actor}} on ${{ github.ref_name}}
on: [push] 
jobs:
  Basic-Workflow: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "Job is executing as part of Basic workflow"
